server:
  port: 8080
spring:
  application:
    name: quan_jia_store
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/quanjia?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: '001124'
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#文件保存路径
quanjia:
  path: E:\project\JavaWeb\file\quanjia\
#发送短信配置
SMS:
#  实例化一个认证对象，入参需要传入腾讯云账户 SecretId 和 SecretKey，此处还需注意密钥对的保密
#  代码泄露可能会导致 SecretId 和 SecretKey 泄露，并威胁账号下所有资源的安全性。以下代码示例仅供参考，建议采用更安全的方式来使用密钥，请参见：https://cloud.tencent.com/document/product/1278/85305
#  密钥可前往官网控制台 https://console.cloud.tencent.com/cam/capi 进行获取
  SecretId:
  SecretKey:
#  短信 SdkAppId
  SdkAppId: test
#  短信签名内容
  SignName: [全佳便利店]
#  模板 ID
  TemplateId: 666
